### Run test remotely
# @timeout 120
POST http://77.234.215.138:34321/run
Content-Type: application/json

{
  "serviceName": "m3403-8",
  "token": "bTgVPIlM5Jbr0T03=8",
  "branch": "lab9_M",
  "accounts": "acc-12",
  "ratePerSecond": "1000",
  "testCount": "200000",
  "processingTimeMillis": "50000"
}

### Stop running test to save credits
# @timeout 120
POST http://77.234.215.138:31234/test/stop/{{serviceName}}
